version: "3.9"

services:
  backend:
    build:
      context: ./apps/backend
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
    env_file:
      - ./apps/backend/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - frontend_node_modules:/app/node_modules # 명명된 볼륨 사용
    command: sh -c "pnpm install && pnpm dev" # 컨테이너 시작 시 의존성 설치

volumes:
  frontend_node_modules: # 명명된 볼륨 정의
